project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments

website:
  site-url: https://v-sekai.github.io/manuals
  repo-url: https://github.com/V-Sekai/manuals
  repo-branch: master
  repo-actions: edit
  title: V-Sekai - Manuals
  page-navigation: true
  navbar:
    logo: 68604884.png
    logo-alt: V-Sekai
    background: primary
    search: true
    left:
      - text: "Changes"
        file: changelog.qmd
      - text: "Decisions"
        file: decisions.qmd
      - text: "Be an Avatar, Visit Places"
        file: be_an_avatar_visit_places.qmd
      - text: "Help Write Documentation"
        file: help_write_documentation.qmd
  page-footer:
    right:
      - icon: github
        href: https://github.com/V-Sekai/manuals
      - icon: twitter
        href: https://twitter.com/VSekaiOfficial
      - icon: discord
        href: https://discord.gg/2YwPmnbqcN    
      - icon: web
        href: https://v-sekai.org/

format:
  epub:
    toc: true
    title: V-Sekai - Manuals
    number-sections: true
    colorlinks: true
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly

filters:
  - quarto

freeze: true

editor: visual
