[project]
name = "manuals"
version = "0.1.0"
description = "Project for roadmap and voting system"
authors = [ { name = "K. S. Ernest (iFire) Lee" } ]
requires-python = ">=3.8"
dependencies = [
    "scipy",
    "pandas",
    "plotly",
    "itables",
    "quarto-cli",
    "starvote",
    "pymoo",
]
